export const apiEndpoints = {
  getAllUsers: '/users/get-all',
  signUp: '/authorization/sign-up',
  signIn: '/authorization/sign-in',
  updateUser: '/users/update',
  findUser: '/users/user',
  getUser: '/users/user',
  restorePassword: '/authorization/restore-password',
  newPassword: '/authorization/new-password',
  verifyOtp: '/authorization/verify-otp',
  deleteUser: '/users/user-delete',
  getOrders: '/orders',
  getTotalSales: '/get-total-sales',
  getAverageSales: '/get-average-sales',
  getNumberOfOrders: '/get-number-of-orders',
  getTotalSalesPerMonth: '/get-total-sales-per-month',
  getTotalSalesPerCategory: '/get-total-sales-for-categories',
  getLastOrders: '/get-last-orders',
};
