export const paths = {
  root: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  restorePassword: '/restore-password',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  confirmCredentials: '/confirm-credentials',
  verify: '/verify',
  newPassword: '/new-password',
  verifyOtp: '/verify-otp',
  verifyEmail: '/verify-email',
  getUser: '/users',
  fillProfile: '/fill-profile',
};
