export const paths = {
  defaultPath: '#',
  root: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  restorePassword: '/restore-password',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  confirmCredentials: '/confirm-credentials',
  verify: '/verify',
  newPassword: '/new-password',
  verifyOtp: '/verify-otp',
  verifyEmail: '/verify-email',
  getUser: '/users',
  publicProfile: '/user/:id',
  profile: '/profile',
  personalInfo: '/profile',
  userList: '/admin/user-list',
  superAdminRoot: '/admin',
  viewUserProfile: '/admin/view-profile/',
  fillProfile: '/fill-profile',
  orders: '#',
  wishlist: '#',
  support: '#',
  logout: '#',
  topVendors: '/top-vendors',
};
