export const paths = {
  root: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  restorePassword: '/restore-password',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  verify: '/verify',
  newPassword: '/new-password',
  verifyOtp: '/verify-otp',
  verifyEmail: '/verify-email',
  getUser: '/user',
  updateUser: '/update',
  fillProfile: '/fill-profile',
  saveGeneralInfo: '/save-general-info',
  saveCardInfo: '/save-card-info',
};
